### ISSUE TITLE
Unreal source files have a black background instead of a dark green shade

### ISSUE THREAD

**Issue by velaris1** [soulshined/IntelliJ-Naysayer88-Color-Theme#1]
When using an Unreal game project, all source files under the engine's path have a pitch black background instead of the expected dark shade of green.

Ex: UE_5.4.1\Engine\Source\Runtime\CoreUObject\Public\UObject\UObjectBaseUtility.h

Source files under the game's path have a green background as intended. Only engine source files are affected.

Thank you for the theme, it's great !

**Comment by velaris1** [comment]
Please disregard, the black background was related to read-only files. :)

**Comment by soulshined** [comment]
All good! I love the easy fixes 😁 this one is just one of those things that is very different from the previous UI or has a weird tie-in to a different component using the same theme setting iirc; but thank god it's configurable by users. 

To your credit, it is different than the previous version of the plugin if you used that, so a keen eye by you if that's the case!

If you want to match it to the green you're most likely speaking about; you can go to:

`Settings > Editor > Color Scheme > General`

and in the 'Text' section, there is an option for `Background in read-only files`

The 2 greens I use in the theme are the following:

```json
"color" : {
   "bg" : "#042327",
   "bg-secondary" : "#2A343E"
}
```

If those aren't what you're looking for let me know! Otherwise thanks for self-helping!
